[[libwasmtime]]
arch = "x86_64"
git-tree-sha1 = "ff23fbddd464e8ec6a130495610fee6b303dc5f6"
libc = "glibc"
os = "linux"

    [[libwasmtime.download]]
    sha256 = "86eada8b26d1a501bf95417c5aa894cedb0c60c1b9c8f8d1dc4b0cfd9c77875d"
    url = "https://github.com/bytecodealliance/wasmtime/releases/download/v0.33.0/wasmtime-v0.33.0-x86_64-linux-c-api.tar.xz"
