[[libwasmtime]]
arch = "x86_64"
git-tree-sha1 = "ce6b9201784101d7af45e5ac601c008be3f6e5ed"
libc = "glibc"
os = "linux"

    [[libwasmtime.download]]
    sha256 = "1ebc4f49fe80f775318d60720a44bc9157049ec0c63f01b7dc25483413f80b56"
    url = "https://github.com/bytecodealliance/wasmtime/releases/download/v0.28.0/wasmtime-v0.28.0-x86_64-linux-c-api.tar.xz"
